- id: "sym-${symdds}-${resolution}"
  desc: "Discretization of ${symdds} to resolution ${resolution}"
  code: 
  - diffeo2dds.DDSFromSymbolic
  - resolution: "${resolution}"
    symdiffeosystem: "${symdds}"


- id: sym-dcl4r-64