- id: dpx1
  desc: Simple horizontal translation back and forth
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] # for visualization
      diffeo: px1
    - original_cmd: [-1]
      diffeo: Ipx1
    topology: plane

- id: drx1
  desc: Simple horizontal translation in one direction
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] # for visualization
      diffeo: R4px1
    topology: plane



- id: dpx3
  desc: Simple horizontal left motion
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] # for visualization
      diffeo: px1
    topology: plane


- id: dpx2
  desc: |
    Simple horizontal translation back and forth,
    but the second motion is double the inverse.
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] 
      diffeo: px1
    - original_cmd: [-2]
      diffeo: R2Ipx1
    topology: plane

- id: dtx1
  desc: |
    Left and right translation (toroidal case).
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] 
      diffeo: tx1
    - original_cmd: [-1]
      diffeo: Itx1
    topology: torus

- id: dtx2
  desc: |
    Only left translation (toroidal case).
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions:
    - original_cmd: [1] 
      diffeo: tx1
    topology: torus

- id: dpr1
  desc: |
    Only rotation
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1] 
      diffeo: pr1
    topology: plane


- id: dcam1
  desc: |
    Camera (pan/tilt)
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0] 
      diffeo: px1
    - original_cmd: [-1, 0] 
      diffeo: Ipx1
    - original_cmd: [0, 1] 
      diffeo: py1
    - original_cmd: [0, -1] 
      diffeo: Ipy1

    topology: plane

- id: dcam3
  desc: |
    Camera (pan/tilt)
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0] 
      diffeo: R3px1
    - original_cmd: [-1, 0] 
      diffeo: R3Ipx1
    - original_cmd: [0, 1] 
      diffeo: R3py1
    - original_cmd: [0, -1] 
      diffeo: R3Ipy1

    topology: plane


- id: dptcam1
  desc: |
    Camera (pan: torus, tilt: plane)
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0] 
      diffeo: tx1
    - original_cmd: [-1, 0] 
      diffeo: Itx1
    - original_cmd: [0, 1] 
      diffeo: py1
    - original_cmd: [0, -1] 
      diffeo: Ipy1
    topology: plane


- id: dptcam3
  desc: |
    Camera (pan: torus, tilt: plane)
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0] 
      diffeo: R3tx1
    - original_cmd: [-1, 0] 
      diffeo: R3Itx1
    - original_cmd: [0, 1] 
      diffeo: R3py1
    - original_cmd: [0, -1] 
      diffeo: R3Ipy1
    topology: plane

- id: dtxty
  desc: |
    Torus xy
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0] 
      diffeo: R3tx1
    - original_cmd: [-1, 0] 
      diffeo: R3Itx1
    - original_cmd: [0, 1] 
      diffeo: R3ty1
    - original_cmd: [0, -1] 
      diffeo: R3Ity1
    topology: plane



- id: dcamz1
  desc: |
    Camera with zoom
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0, 0] 
      diffeo: px1
    - original_cmd: [-1, 0, 0] 
      diffeo: Ipx1
    - original_cmd: [0, 1, 0] 
      diffeo: py1
    - original_cmd: [0, -1, 0] 
      diffeo: Ipy1
    - original_cmd: [0, 0, 1] 
      diffeo: pz1
    - original_cmd: [0, 0, -1] 
      diffeo: Ipz1
    topology: plane

- id: drob1
  desc: |
    Robot with differential drive
  code:
  - diffeo2dds.SymDiffeoSystem
  - actions: 
    - original_cmd: [1, 0, 0] 
      diffeo: px1
    - original_cmd: [-1, 0, 0] 
      diffeo: Ipx1
    - original_cmd: [0, 0, 0.1] 
      diffeo: pr1
    - original_cmd: [0, 0, -0.1] 
      diffeo: Ipr1
    topology: plane





