- id: lena
  desc: Simple test image
  code: 
    - diffeo2dds.library.load_image
    - filename: images/lena.jpg

- id: "png-${name}"
  desc: "Load PNG file named ${name}"
  code: 
    - diffeo2dds.library.load_image
    - file:filename: "images/${name}.png"
