

- id: "I${diffeo}"
  desc: "Inverse of ${diffeo}"
  code:
  - diffeo2s.library.make_inverse
  - id_diffeo: "${diffeo}"


# - id: "${diffeo1}+${diffeo2}"
#   desc: "${diffeo1} +${diffeo2}"
#   code:
#   - diffeo2s.make_chain
#   - diffeos: ["${diffeo1}", "${diffeo2}"]

- id: "Itx1"

- id: "R2${diffeo}"
  desc: "Double application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 2

- id: "R3${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 3

- id: "R4${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 4


- id: "R5${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 5

- id: "R3tx1"


# - id: "tchain1"
#   desc: composition test
#   code:
#   - diffeo2s.library.make_chain
#   - diffeos: [Itr1, tx1, tr1]

- id: "pchain1"
  desc: composition test
  code:
  - diffeo2s.library.make_chain
  - diffeos: [Ipx1, pr1, px1]
