

- id: "I${diffeo}"
  desc: "Inverse of ${diffeo}"
  code:
  - diffeo2s.library.make_inverse
  - id_diffeo: "${diffeo}"


# - id: "${diffeo1}+${diffeo2}"
#   desc: "${diffeo1} +${diffeo2}"
#   code:
#   - diffeo2s.make_chain
#   - diffeos: ["${diffeo1}", "${diffeo2}"]

- id: "Itx1"

- id: "R2${diffeo}"
  desc: "Double application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 2

- id: "R3${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 3

- id: "R4${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 4


- id: "R5${diffeo}"
  desc: "Triple application of ${diffeo}"
  code:
  - diffeo2s.library.repeat
  - id_diffeo: "${diffeo}"
    times: 5

- id: "R3tx1"