# - id: "test_dds_estimator_fast_${match}_${displ}"
#   desc: "Faster estimator (optimized), displacement ${displ}, match ${match}" 
#   code:
#   - diffeo2dds_learn.library.DiffeoSystemEstimatorFlexible
#   - diffeo_action_estimator:
#     - diffeo2dds_learn.library.DiffeoActionEstimatorSimple
#     - diffeo2d_estimator: 
#       - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
#       - max_displ: "0.${displ}"
#         inference_method: "${match}"  # order, sim, quad

# - id: "test_dds_estimator_fast_${match}_${displ}_unc_${score}"
#   desc: "Faster estimator (optimized), displacement ${displ}, match ${match}. New uncertainty based." 
#   code:
#   - diffeo2dds_learn.library.DiffeoSystemEstimatorFlexible
#   - diffeo_action_estimator:
#     - diffeo2dds_learn.library.DiffeoActionEstimatorNewUnc
#     - score: "${score}"
#       diffeo2d_estimator: 
#       - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
#       - max_displ: "0.${displ}"
#         inference_method: "${match}"  # order, sim, quad

# - id: "test_dds_estimator_simple_${match}_${displ}"
#   desc: "Faster estimator (optimized), displacement ${displ}, match ${match}" 
#   code:
#   - diffeo2dds_learn.library.DiffeoSystemEstimatorFlexible
#   - diffeo_action_estimator:
#     - diffeo2dds_learn.library.DiffeoActionEstimatorSimple
#     - diffeo2d_estimator: 
#       - diffeo2d_learn.library.DiffeomorphismEstimatorSimple
#       - max_displ: "0.${displ}"
#         match_method: "${match}" # continuous, binary


# - id: "test_dds_estimator_refine_${displ}"
#   desc: "" 
#   code:
#   - diffeo2dds_learn.library.DiffeoSystemEstimatorFlexible
#   - diffeo_action_estimator:
#     - diffeo2dds_learn.library.DiffeoActionEstimatorSimple
#     - diffeo2d_estimator: 
#       - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
#       - max_displ: ["0.${displ}", "0.${displ}"]
#         g: 5
#         gamma: 1.3
#         desired_resolution_factor: 2.0
#         change_threshold: 0.001

- id: "test_ddsest_${action_estimator}"
  desc: "" 
  code:
  - diffeo2dds_learn.library.DiffeoSystemEstimatorFlexible
  - diffeo_action_estimator: "${action_estimator}"


- id: test_ddsest_reg_fast_order
- id: test_ddsest_reg_fast_sim
- id: test_ddsest_reg_simple_cont
- id: test_ddsest_reg_simple_bin
- id: test_ddsest_reg_refine1
- id: test_ddsest_unc_fast_order
- id: test_ddsest_unc_fast_sim
- id: test_ddsest_unc_simple_cont
- id: test_ddsest_unc_simple_bin
- id: test_ddsest_unc_refine1
- id: test_ddsest_unc_refine2
  

# - id: test_dds_estimator_simple_continuous_10  
# - id: test_dds_estimator_simple_binary_10  
# - id: test_dds_estimator_fast_order_10  
# - id: test_dds_estimator_fast_sim_10   
# - id: test_dds_estimator_fast_order_10_unc_norm
# - id: test_dds_estimator_fast_sim_10_unc_normrel
