- id: fast_order
  desc: ""
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
  - inference_method: order 

- id: fast_sim
  desc: ""
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
  - inference_method: sim

- id: simple_cont
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorSimple
  - match_method: continuous

- id: simple_bin
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorSimple
  - match_method: binary

- id: "refine1"
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 2.0
    change_threshold: 0.005
    min_shape: [32, 32]

- id: "refine2"
  desc: "Slightly less picky for the threhsold" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 2.0
    change_threshold: 0.05
    min_shape: [32, 32]
