- id: fast_order
  desc: ""
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
  - inference_method: order 

- id: fast_sim
  desc: ""
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorFaster
  - inference_method: sim

- id: simple_cont
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorSimple
  - match_method: continuous

- id: simple_bin
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorSimple
  - match_method: binary

- id: "refine0"
  desc: "Same resolution"
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 1.0
    change_threshold: 0.8
    min_shape: [32, 32]
    inference_method: order
    stop_at_convergence: true


- id: "refine1"
  desc: "" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 2.0
    change_threshold: 0.8
    min_shape: [32, 32]
    inference_method: order
    stop_at_convergence: true


- id: "refine2"
  desc: "Slightly less picky for the threhsold" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 2.0
    change_threshold: 0.8
    min_shape: [32, 32]
    inference_method: order
    stop_at_convergence: true

- id: "refine3"
  desc: "Min shape is higher (64x32)"  # exp25
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    desired_resolution_factor: 1.0
    change_threshold: 0.8
    inference_method: order
    min_shape: [64, 32]
    stop_at_convergence: true


- id: "refine_exp26"
  desc: "Min shape is higher (64x32)" 
  code: 
  - diffeo2d_learn.library.DiffeomorphismEstimatorDoubleRefine
  - g: 5
    gamma: 1.3
    stop_at_convergence: true
    inference_method: sim
    desired_resolution_factor: 1.0
    change_threshold: 0.9
    min_shape: [64, 32]


